---
- name: "Customizing Dev Environment"
  hosts: localhost
  connection: local

  vars:
    node_version: "20.10.0"
    node_arch: "x64"
    go_version: "1.21.5"
    go_arch: "linux-amd64"
    java_version21: "21"
    java_arch21: "jdk-21_linux-x64_bin"
    java_version17: "17"
    java_arch17: "jdk-17_linux-x64_bin"
    maven_version: "3.9.6" 
    dbeaver_deb_url: "https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb"
    dbeaver_deb_file: "/tmp/dbeaver-ce_latest_amd64.deb"
    compose_version: 2.23.3


  roles:
    - {role: docker, become: yes}
    - {role: go , become: yes}
    - {role: java , become: yes}
    - {role: node , become: yes}
    - {role: tmux , become: yes}
    - {role: dbeaver , become: yes}
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - golang.Go
            - ms-vscode.vscode-typescript-next
            - bradlc.vscode-tailwindcss
            - mads-hartmann.bash-ide-vscode
            - snyk-security.snyk-vulnerability-scanner
            - redhat.vscode-yaml
            - vscjava.vscode-java-pack
            - redhat.ansible
    - role: vscode-settings
