---
- name: "Install Tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copying Tmux Config"
  copy:
    src: .tmux.conf
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644