---
- name: Download Node.js archive
  get_url:
    url: "https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-{{ node_arch }}.tar.gz"
    dest: "/tmp/node.tar.gz"
    validate_certs: yes

- name: Extract Node.js archive
  ansible.builtin.unarchive:
    src: "/tmp/node.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: Handle Symbolic Link ignore_errors
  block:
    - name: Create symbolic links for Node.js binaries
      ansible.builtin.command:
        cmd: "ln -s /usr/local/node-v{{ node_version }}-linux-{{ node_arch }}/bin/node /usr/local/bin/node"
  rescue:
   - name: Print when errors
     ansible.builtin.debug:
       msg: "Error Caught"      

    
