---
- name: Handle errors in NodeJS installing
  block:
    - name: Add NodeJS to APT Repositories
      ansible.builtin.command: "{{ item }}"
      loop: 
        - "wget https://deb.nodesource.com/setup_21.x -O /tmp/setup_21.x"
        - "chmod +x /tmp/setup_21.x"
        - "/tmp/setup_21.x"
        - "rm /tmp/setup_21.x"

    - name: Install NodeJS
      package:
        name: nodejs
        state: present
      when: ansible_os_family == 'Debian'
  rescue:
   - name: Print when errors
     ansible.builtin.debug:
       msg: "Error Caught"      

    
